version: '3'
services:
  postgres:
    image: postgres:15
    env_file: configs/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"

  auth:
    build: src
    env_file: configs/.env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./logs:/opt/app/logs
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -sS http://127.0.0.1:8000 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
